### ISSUE TITLE
No module named 'FactorizedViT3D'

### ISSUE THREAD

**Issue by KongMini** [tom1193/time-distance-transformer#1]
<img width="910" alt="image" src="https://user-images.githubusercontent.com/64362024/236979274-bff19526-766b-47fe-9ab7-3ec3686d7bc6.png">
I can't find the file FactorizedViT3D. Can you send me that code file?

**Comment by tom1193** [comment]
That model was from an different experiment that didn't pan out. The dependency was deleted edc6f5b60ca333a297a9b033f6a9dfdebdd46c99
